### ISSUE TITLE
Definición del problema a resolver

### ISSUE THREAD

**Issue by juanmi-gh** [tddgrupo4/TDD-Grupo-4#4]
## Descripción de alto nivel

*Como un **integrante del equipo 4** necesito una **definir el problema a resolver** para poder **comenzar a tomar las decisiones técnicas** *

## Dado/Y/Entonces/Cuando

Describir las diferentes posibilidades en diferentes escenarios.

**Comment by leolplex** [comment]
### Propuesta #1: Búsqueda y compra de tickers a la champions league:

- Como aficionado al PSG necesito buscar el calendario de mi equipo en mi hora local para planear mi viaje.
- Como aficionado al PSG necesito reservar los tickets de champions league en los que este interesado.
- Como aficionado al PSG necesito reservar los tickets de transporte al estadio los días en que voy a ir al estadio.

**Comment by juanmi-gh** [comment]
Hola @leolplex, gracias por el aporte.

¿Tienes en mente alguna fuente de datos de la que sacar la información para los partidos, tickets, transporte..?

Así a primera vista me parece demasiado ambicioso, pero quizás me falta información.

**Comment by juanmi-gh** [comment]
Encontré esto https://www.football-data.org/coverage

**Comment by gedsakal** [comment]
**Propuesta #2: Indicador del Tiempo**

* Como usuario quiero saber que tiempo hace actualmente en el sitio que estoy
* Como usuario quiero preever el tiempo en localidad X para hora Y
* Como usuario quiero saber si el finde semana X va hacer buen tiempo para una escapada en el region Y

**Comment by gedsakal** [comment]
Mi opinion... sobre la reserva de tickets, transporte me parece complejo de proveer un resultado aceptable para usuario (una reserva es algo ambiguo), compicado de testear y quizás demasiado complejo para un proyecto te pruebas.

**Comment by leolplex** [comment]
> Hola @leolplex, gracias por el aporte.
> 
> ¿Tienes en mente alguna fuente de datos de la que sacar la información para los partidos, tickets, transporte..?
> 
> Así a primera vista me parece demasiado ambicioso, pero quizás me falta información.

Entiendo, no tengo más información me parece la idea del tiempo mejor.

**Comment by gedsakal** [comment]
La idea inicial es usar una api de terceros que nos dan los datos en formato XML, JSON, o PHP. 

Aqui nuestro proyecto sería nada más que de crear un formulario y mostrar los datos de respuesta al usuario para responder al su problema.

¿O es demasiado sencillo? 

Una api de terceros como ejemplo: https://api.tutiempo.net/

**Comment by juanmi-gh** [comment]
Ok, pues vamos con "El tiempo", me parece buena idea para dar comienzo. 

Si vemos que nos quedamos con ganas siempre podríamos ampliar el scope con nuevas épicas o complicarnos un poco más.

Según el curso, los siguientes pasos serían:
1. Definir épica (problema a resolver desde el punto de vista funcional, sin entrar en detalles de implementación)
2. Crear tablero tipo kanban

No sé si me dejo algo. Pero bueno, vamos a viendo que los arranques siempre cuestan un poco más.

**Comment by JJ** [comment]
¿Necesitáis un poco de ayuda aquí para progresar al hito 1?
